### PR TITLE
Namenlos v0.0.17

### PR DESCRIPTION
**Pull request by ioerror**
This change updates the PKI to use the current experimental (no guarantees!) post-quantum namenlos Katzenpost network configuration. It also updates the dependency in go.mod to track v0.0.17 of Katzenpost.

### CODE REVIEW

**Comment by ioerror** [comment]
image

**Review by david415 — APPROVED** [review]
lgtm

**Comment by ioerror** [comment]
Worth noting is that this tracks the current namenlos network catshadow config, so we have removed these two options:
```
  DisableDecoyTraffic = false
  PreferedTransports = ["onion"]
```

Do we want to disable these in Katzen?

**Comment by ioerror** [comment]
Additionally this disables decoy traffic while we measure and test the network:
```
DisableDecoyTraffic = true
```

This should be set to false before we cut a release.

**Comment by ioerror** [comment]
The current outstanding issue relates to the gogio replacement:
```
$ make docker-build-android 
if ! podman images|grep katzen/android_sdk; then \
	podman build --no-cache -t katzen/android_sdk -f Dockerfile.android .; \
fi
localhost/katzen/android_sdk  latest      dc185d4e9705  36 minutes ago  5.4 GB
if [ ! -e sign.keystore ]; then \
	podman run --rm -v "/home/user/Documents/src/katzen":/go/build katzen/android_sdk bash -c "keytool -genkey -keystore sign.keystore -storepass password -alias android -keyalg RSA -keysize 2048 -validity 10000 -noprompt -dname CN=android"; \
fi
podman run --rm -v "/home/user/Documents/src/katzen":/go/build katzen/android_sdk bash -c "go install gioui.org/cmd/gogio && CGO_CFLAGS_ALLOW="-DPARAMS=sphincs-shake-256f" gogio -arch arm64,amd64 -x -target android -appid org.mixnetworks.katzen -version 1 -signkey sign.keystore -signpass password ."
go: downloading github.com/mixmasala/gio v0.0.0-20221110164814-c517124e183a
missing go.sum entry for module providing package gioui.org/cmd/gogio
make: *** [Makefile:22: docker-build-android] Error 1
```

**Review by david415 — DISMISSED** [review]

**Comment by ioerror** [comment]
I've now added a commit that sets `PreferedTransports = ["onion"]` for the Tor enabled config, and both now set `DisableDecoyTraffic=false`.

**Comment by ioerror** [comment]
I have run `katzen` that built in docker (`docker-build-linux`) from this branch on GNU/Linux. It is functional with and without Tor.

Katzen over the namenlos network is working to exchange messages with another katzen client on the same machine using a different state file (in all three combinations for both clients: with tor and without, without and without, and with and with). 

As we once had pond bonds, I think now we have functional katzentatzen for peer discovery. 

Katzentatzen was successful for peer discovery and we were able to exchange messages after the Katzentatzen (powered by pandaprime) was completed.

**Review by david415 — APPROVED** [review]

**Pull request merged**
